# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-api:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run: 
        name: "create venv"
        command: |
          python3 -m venv ~/.devops
      - run:
          name: "Install dependencies"
          command: |
            make install
      - run:
          name: "Check syntaxt code"
          command: |
            make link

workflows:
  default:
    jobs:
      - build-api
